image: python:3.12

stages:
  - build
  - deploy

before_script:
  # Install dependencies
  - pip install poetry
  - poetry install
  - pip install mkdocs mkdocs-material

build_docs:
  stage: build
  script:
    # Run your Makefile targets to generate docs
    - make docs pylode
    # Prepare public folder for GitLab Pages
    - rm -rf public
    - mkdir -p public
    # Copy LinkML Markdown docs
    - cp -r schemas/docs/* public/
    # Copy pyLODE docs into a subfolder, e.g., pylode/
    - mkdir -p public/pylode
    - cp -r schemas/pylode/* public/pylode/
    # Optional: list files for debugging
    - ls -R public
  artifacts:
    paths:
      - public
  only:
    - main