image: python:3.12

pages:
  stage: deploy
  script:
    # install dependencies
    - pip install poetry mkdocs mkdocs-material pylode linkml
    - poetry install

    # generate LinkML docs + pyLODE HTML
    - make docs pylode

    # build mkdocs into site/
    - mkdocs build -d site

    # organize outputs into public/
    - rm -rf public
    - mkdir -p public/mkdocs
    - mkdir -p public/pylode
    - cp -r site/* public/mkdocs/
    - cp -r schemas/pylode/* public/pylode/
    - ls -R public   # debug: list what will be published

  artifacts:
    paths:
      - public
  only:
    - main